/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lms.gui;

/**
 *
 * @author 'M
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookListButton = new javax.swing.JButton();
        AddEditBooksButton = new javax.swing.JButton();
        MemberListButton = new javax.swing.JButton();
        AddEditMemberButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        BookListButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BookListButton.setText("Book List");
        BookListButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookListButtonMouseClicked(evt);
            }
        });

        AddEditBooksButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AddEditBooksButton.setText("Add / Edit Books");
        AddEditBooksButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddEditBooksButtonMouseClicked(evt);
            }
        });

        MemberListButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MemberListButton.setText("Member List");
        MemberListButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MemberListButtonMouseClicked(evt);
            }
        });
        MemberListButton.addActionListener(this::MemberListButtonActionPerformed);

        AddEditMemberButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AddEditMemberButton.setText("Add / Edit Members");
        AddEditMemberButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddEditMemberButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BookListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddEditBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MemberListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddEditMemberButton))
                .addGap(151, 151, 151))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddEditBooksButton, AddEditMemberButton, BookListButton, MemberListButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(BookListButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddEditBooksButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MemberListButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddEditMemberButton)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookListButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookListButtonMouseClicked
        new BookListFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BookListButtonMouseClicked

    private void AddEditBooksButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEditBooksButtonMouseClicked
        new AddEditBookFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddEditBooksButtonMouseClicked

    private void MemberListButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberListButtonMouseClicked
        new MemberListFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MemberListButtonMouseClicked

    private void AddEditMemberButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEditMemberButtonMouseClicked
        new AddEditBookFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddEditMemberButtonMouseClicked

    private void MemberListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberListButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberListButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEditBooksButton;
    private javax.swing.JButton AddEditMemberButton;
    private javax.swing.JButton BookListButton;
    private javax.swing.JButton MemberListButton;
    // End of variables declaration//GEN-END:variables
}
